### PR TITLE
fix: clear cmdline area based on cmdheight

### LINKED ISSUE #77: Clear status line after hop when `cmdheight > 1`
Re-raising this issue from the original repo: https://github.com/hadronized/hop.nvim/issues/276
> When I use `:HopChar1`, the statusline changes to `Hop 1 Char: `. However, this does not go away after hopping when using more than 1 line for the statusline (when the `cmdheight` option is greater than 1).
>
> Would it be possible to clear the prompt after hopping no matter how large the statusline is?

### PR DESCRIPTION
**Pull request by henry-hsieh**
Fix #77. Emit `vim.api.nvim_echo` based on the height of the command line. The `vim.api.nvim_echo` did not append newline after the message. Therefore, the message should be newline ('\n') instead of empty.

### CODE REVIEW

**Comment by monkoose** [comment]
This have made the plugin with `hint_char1()` unusable and showing "press ENTER or type command to continue" two times before actually accepting char, when invoked from the map. For some reason `:lua require("hop").hint_char1()` is working fine.

**Comment by monkoose** [comment]
Just revert it. Based on the commit it is not how the issue #77 should be fixed.

**Comment by henry-hsieh** [comment]
You should provide the minimal reproduce steps. I tested with nvim-0.9.5, nvim-0.10.0 and nvim-0.11.3 with minimal setup (only installed hop.nvim). Not showing the message you said above. I tested `:HopChar1` and `:lua require("hop").hint_char1()`, both are working correctly. I cannot understand how you called `hint_char1()` without `require("hop")`.

I'm here to explain why I use this approach to fix the issue. First, the cmdline is refreshed when you entering the command mode (:) or use a keymap that affect the cmdline (ex: print). However, when you do the Hop command, the multiple prints are just showing line by line like below:

圖片

This is due to that Neovim won't immediately redraw the screen when you are executing the same command, which will clear you cmdline. When the print line number overs the cmdline height, the cmdline will restart from top:

圖片

Therefore, my solution is very simple, just make lines overflow the cmdline height for every keystrobe you entered, and also before leaving the Hop command. BTW, if you only use `print("")` or `vim.api.nvim_echo({}, false, {})`, the Neovim won't insert a newline for the commands. That's why I replicate the newline characters.

If you have better solution to resolve the #77, please provide it and explain it. I'm glad to revert the commit.

**Comment by monkoose** [comment]
The problem is, I can't reproduce #77 issue. So it is you or the author of #77 who should have attached reproduction steps at first. Because for me it is cleared properly for `hint_char1`.

Add an keymap for it with `vim.keymap.set()` and try keymap. Not `:Hop..` or `:lua require..` from command line. And then invoke it with this keymap.

At least echo message shouldn't be higher then command line, because when you pasting `"\n"` with echo it is actually echoing two lines (one is "\n", and another is empty line) for cmdline with the default height of one. So my best guess it should be `vim.o.cmdheight - 1` for repeat string.

Author of #77 talking about HopChar1 and your example is some multichar string.

Edit:
I can reproduce `:HopPattern` issue, but can't `HopChar1` with any cmdheight size.

**Comment by henry-hsieh** [comment]
Thanks for you clarification. I think the problem is that, when you directly execute the require("hop").hint_char1(), the printed line number is not equal to you called it with keystrobe, interesting.

It seems one more line is printed when you evoke it with key. I have to do more tests.

**Comment by monkoose** [comment]
You can fix your issue swapping `vim.cmd.redraw()` with `vim.cmd.mode()`. It would do the screen clear and prevents this multiline issue. In vim it was achieved with `:redraw!`, but in neovim to do the same as `:redraw!` you need to use `:mode`. But it maybe can add some flickering (not happening for me, but it can be depended on terminal emulator and how slow full screen redrawing is).

I would do it like so, changing `vim.cmd.redraw()` lines to:
```lua
if vim.o.cmdheight > 1 then
  vim.cmd.mode()
else
  vim.cmd.redraw()
end
```

File: lua/hop/init.lua [hunk 1]
```diff
@@ -210,7 +210,7 @@ function M.get_input_pattern(prompt, maxchar, opts)
       M.quit(hs)
     end
   end
-  api.nvim_echo({}, false, {})
+  api.nvim_echo({ { string.rep('\n', vim.o.cmdheight) } }, false, {})
```
Comment (henry-hsieh) [inline lua/hop/init.lua:213]: I think the correct answer is to schedule the empty print and the redraw.
```lua
  vim.schedule(function()
    api.nvim_echo({  }, false, {})
    vim.cmd.redraw()
  end)
```

Comment (henry-hsieh) [reply lua/hop/init.lua:213]: This is the differences drew by GPT.
```
────────────────────────────────────────────────────────────────────────────
Case A:  vim.cmd.redraw()        | Case B:  vim.cmd.mode()
────────────────────────────────────────────────────────────────────────────
PHASE 1: Mapping Execution       | PHASE 1: Mapping Execution
- cmdline still shows old        | - cmdline still shows old
  ":command".                    |   ":command".
- :redraw schedules refresh      | - :mode immediately prints
  for later, no overwrite yet.   |   "mode: n" (or similar).
                                 | - Old cmdline instantly replaced.
────────────────────────────────────────────────────────────────────────────
PHASE 2: Mapping Ends             | PHASE 2: Mapping Ends
- Event loop processes redraw →  | - No extra redraw needed, message
  old ":command" finally gone.   |   already replaced cmdline.
- Feels like a "delayed clear".  | - Feels instant.
────────────────────────────────────────────────────────────────────────────



────────────────────────────────────────────────────────────────────────────
Case C:  vim.schedule(function() vim.cmd([[echo "" | redraw]]) end)
────────────────────────────────────────────────────────────────────────────
PHASE 1: Mapping Execution
- cmdline still shows old ":command".
- Nothing printed yet.
────────────────────────────────────────────────────────────────────────────
PHASE 2: Mapping Ends
- Scheduled function runs *immediately after* mapping exits.
- `echo ""` prints empty line → overwrites cmdline instantly with blank.
- `redraw` refreshes the screen right away.
- Old ":command" is gone *instantly* (like Case B) but without showing any text.
────────────────────────────────────────────────────────────────────────────
```

Comment (monkoose) [reply lua/hop/init.lua:213]: You have implememnted this PR with AI too?

It doesn't fkn understand what `:mode` is.

**Comment by monkoose** [comment]
@smoka7 revert this useless PR

File: lua/hop/init.lua (hunk 1 above)
Comment (henry-hsieh) [reply lua/hop/init.lua:213]: No. But you're right about it misunderstood the `:mode`. I'll remove it.

**Comment by spamwax** [comment]
@smoka7 can we revert or fix the problem this is causing please? I am having the same issue as @monkoose and it is basically making the plugin useless
